### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by doncat99** [timeolord/Reinforcement-Learning-Stock-Trader#1]
missing startRay.sh file

**Comment by timeolord** [comment]
The startRay.sh file you'll have to create yourself, although if you don't plan on running this on multiple systems its not needed. If your only running it on your local system just start a Ray instance on console and then run the python script.
I've pasted an example below for the startRay.sh file, just fill in the all caps parts, and write another startRay.sh file on the node to join the ray instance you started in this script. If you need help let me know. I honestly didn't expect anyone to use this so there's no documentation at all.

#!/bin/bash
cd ~/venvs/ReinforcementLearning/binsource activateray start --head
cd /home/HEAD/Desktop/ReinforcementLearningProjects
sshpass -p PASSWORD ssh NODE@192.168.0.IP "cd Desktop/ ; ./startRay.sh"

**Comment by widebowl** [comment]
Dear timeolord.
Thank you for your wonderful work.
I've been trying to apply AI to my investments, but the results haven't been very good.
So I want to study your code and apply it to investment.
I'm not comfortable writing the details here, 
so if you reply to my email, I'd like to send you my detailed thoughts.
My email is widebowl@daum.net
Thank you.
