### ISSUE TITLE
Contact info?

### ISSUE THREAD

**Issue by SheldonCurtiss** [timeolord/Reinforcement-Learning-Stock-Trader#4]
Hey man - I've been working on similar projects for the past something like 3 months straight and would love to connect if you had time regarding questions and optimizations.
Do you have any contact info? I.e discord?

**Comment by timeolord** [comment]
Yeah for sure you can message me at TimeOlord#9138.

**Comment by SheldonCurtiss** [comment]
Added I have a dumb name starting with 'king' - will message you on there.
